from .remove_pictures import remove_pictures
from .remove_picture_text_blocks import remove_picture_text_blocks
from .remove_bold import remove_bold
from .remove_italic import remove_italic
from .remove_horizontal_rules import remove_horizontal_rules
from .remove_br_tags import remove_br_tags
from .translate_md_table import translate_md_table
from .remove_whitespace_lines import remove_whitespace_lines
from .collapse_blank_lines import collapse_blank_lines
from .remove_arrow import remove_arrow
from .merge_headers import merge_headers
